id: A28152DA1
base_file: f6D4E.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:37:20.774192
  last_modified_at: 2022-06-17 11:37:20.774215
