id: A28152DA1
base_file: fE142.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:37:20.783689
  last_modified_at: 2022-06-17 11:37:20.783696
