id: A28152DA1
base_file: f8DA2.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:37:20.780287
  last_modified_at: 2022-06-17 11:37:20.780298
